version: "3.7"

services:
  app:
    build: .
    container_name: app
    restart: unless-stopped
    ports:
      - '3333:3333'
    environment:
      - NUXT_PORT=3333
    volumes:
      - ./:/app
    networks:
      - nuxt-network
networks:
  nuxt-network:
    driver: bridge