version: "3.8"

services:
  app:
    build:
      context: .
      target: development
    container_name: app
    restart: unless-stopped
    command: npm run dev
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules