version: "3.7"

services:
  app:
    build: .
    container_name: app
    restart: unless-stopped
    command: npm run dev
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
    networks:
      - nuxt-network
networks:
  nuxt-network:
    driver: bridge