version: "3.8"

services:
  app:
    build:
      context: .
      target: dev-stage
    container_name: app
    restart: unless-stopped
    command: npm run dev
    ports:
      - '3000:3000'
    volumes:
      - ./:/app/
      - /app/node_modules